### ISSUE TITLE
Wrong order of bit

### ISSUE THREAD

**Issue by mancausoft** [jakubfi/v9ttd#1]
@jakubfi 
I read on the readme:

```
-c/--chlist CHLIST - Input channel position list specified as: P,7,6,5,4,3,2,1,0 (P=parity, 0=LSB). Default is: 8,7,6,5,4,3,2,1,0
```

But for IBM standard the track 0 is the MSB not the LSB. 
This can be create a confusion when extract signal from a real tape.

From a tape driver documentation:
![photo_2016-05-19_12-55-38](https://cloud.githubusercontent.com/assets/1152781/15391392/39e97b22-1dc1-11e6-98f6-1dcdf9b114ad.jpg)

**Comment by jakubfi** [comment]
The option in question takes logic analyzer _channel_ numbers as an argument, not _track_ numbers.

How channels are assigned to tracks depend on the channel _position_ in the list. Description is given to denote where the least and most significant tracks should be placed. Track enumeration standard doesn't apply here. There were at least three standards in use: little endian, big endian and by the physical position on a tape; IBM standard is just one of them. '-c' option is made that way so tool is standard agnostic and it's up to the user to properly locate tracks according to manufacturer's standards.

Short '-c' option description unfortunately needs do be minimal, so it may create confusion. I think v9ttd documentation will clear all the potential doubts.

**Comment by mancausoft** [comment]
As far as I know the ibm standard is  the standard used by all 9 track reel tape, all documentation i read on this type of tape the name of the 9 track as: P 0 1 2 3 4 5 6 7, P for partity 0 for the MSB and 7 for LSB.

**Comment by jakubfi** [comment]
From the ECMA-62 standard definition:
![screenshot_20160519_163434](https://cloud.githubusercontent.com/assets/1270167/15397230/9a90ce9e-1ddf-11e6-9ffa-1c332a7e8749.png)
From the HP 7970B/E Maintenance seminar handouts:
![screenshot_20160519_164027](https://cloud.githubusercontent.com/assets/1270167/15397406/736a5e6a-1de0-11e6-9ee0-529d21272777.png)

But as I've mentioned before - this doesn't matter here. '-c' option does not take track numbers, nor the description mentions them.

**Comment by mancausoft** [comment]
👍
